{{- if .Values.klone.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-worker
  namespace: {{ .Values.klone.namespace }}
  labels:
    app: k3s-worker
    {{- include "klone.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.klone.k3s.worker.replicas }}
  selector:
    matchLabels:
      app: k3s-worker
  template:
    metadata:
      labels:
        app: k3s-worker
    spec:
      containers:
        - name: k3s-agent
          image: {{ .Values.klone.k3s.image }}
          securityContext:
            privileged: true
          args:
            - agent
            - --server
            - https://k3s-control-plane.{{ .Values.klone.namespace }}.svc.cluster.local:6443
            - --token
            - {{ .Values.klone.k3s.token }}
          volumeMounts:
            - name: k3s-agent-data
              mountPath: /var/lib/rancher/k3s
      volumes:
        - name: k3s-agent-data
          emptyDir: {}
{{- end }}
