{{- if .Values.klone.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k3s-data
  namespace: {{ .Values.klone.namespace }}
  labels:
    app: k3s-control-plane
    {{- include "klone.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.klone.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.klone.storage.size }}
{{- end }}
