{{- if .Values.klone.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: klone-terminal
  namespace: {{ .Values.klone.namespace }}
  labels:
    app: klone-terminal
    {{- include "klone.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: klone-terminal
  ports:
    - name: terminal
      port: 80
      targetPort: 7681
{{- end }}
