{{- if .Values.klone.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: k3s-control-plane
  namespace: {{ .Values.klone.namespace }}
  labels:
    app: k3s-control-plane
    {{- include "klone.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: k3s-control-plane
  ports:
    - port: 6443
      targetPort: 6443
{{- end }}
