{{- if .Values.kloneApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: klone
  namespace: {{ .Values.kloneApi.namespace }}
  labels:
    app: klone
    {{- include "klone.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: klone
  ports:
    - name: http
      port: 80
      targetPort: 8000
{{- end }}
