{{- if .Values.kloneApi.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: klone
  namespace: {{ .Values.kloneApi.namespace }}
  labels:
    {{- include "klone.labels" . | nindent 4 }}
{{- end }}
