{{- if .Values.argocd.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "klone-operator.fullname" . }}-argocd-credentials
  namespace: {{ include "klone-operator.namespace" . }}
  labels:
    {{- include "klone-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.argocd.username | default "admin" | quote }}
  password: {{ .Values.argocd.password | quote }}
{{- end }}
